### ISSUE TITLE
the x86_64 examples do not work on Windows

### ISSUE THREAD

**Issue by rexim** [tsoding/bm#113]
introduced in #112

**Comment by kolumb** [comment]
I rewrote `basm2nasm.c` so it can create `123i.asm` that works on Windows. For example, this is INST_NATIVE changes:
https://www.diffchecker.com/U9TcvO5E

I wanted to ask, if I would create a PR, how should I organize output of resulting executables?

Maybe `basm2nasm` could take a flag with architecture? For example the same flags that `nasm` takes:
>basm2nasm -felf64 <input.basm>
basm2nasm -fwin64 <input.basm>

Also maybe `bulld/examples` folder could contain `bm`, `unix` and `win` folders?
