### ISSUE TITLE
Suggestion: File marker, versioning

### ISSUE THREAD

**Issue by catull** [tsoding/bm#14]
The birtual machine file could have a marker, like "BRCH".

That way, the `magic(5)` database and `file(1)`command would tell the user that it is a `Birtual Machine binary file`.
That marker could be followed by a version, say a 32-bit.

Evidently, the `bme` would have to skip the two fields before executing any instructions.

**Comment by rexim** [comment]
@catull sounds good. We will do that eventually. Thanks for the suggestion!
