### ISSUE TITLE
Differing definitions of `int64_t` on macos

### ISSUE THREAD

**Issue by zhiayang** [tsoding/bm#16]
On macos (no idea about "real" BSD), `int64_t` is defined as `long long`, while on linux it's defined as `long`. This causes issues with the printf formatting generating warnings (it won't actually affect the runtime since `long` is still also 8 bytes)

There's `inttypes.h` and `PRId64` nonsense, but that might get ugly...

**Comment by rexim** [comment]
@zhiayang thanks for bringing this up! I hope we will come with a reasonable solution eventually.

**Comment by rexim** [comment]
@zhiayang oh btw, @kolumb tried to address that in #23. Do you still get the warnings on the latest commit?

**Comment by zhiayang** [comment]
yep, it's fixed already!
sadge syntax though
