### ISSUE TITLE
file(1) maintainer deems magic marker "really weak" for 2021

### ISSUE THREAD

**Issue by catull** [tsoding/bm#185]
The maintainer of file(1) command has accepted a patch to support the Birtual Machine.

However, he [states](https://bugs.astron.com/view.php?id=226#c3535)

> I added it, but the magic is really weak. It is 2021 and we are making 2 byte magic entries? Please let the developers know that they should have at least a 4 byte magic. If there are conflicts/complaints in the future it will be removed.

Perhaps the magic marker should be "bomb", for  **B**orn **O**f **M**ighty **B**irtualization.

I checked, "bomb" is not taken yet.

**Comment by aodhneine** [comment]
We could use `0xa4 0x01 0x6d 0x62`, which deserialised is `420 bm`.

**Comment by aodhneine** [comment]
```diff
diff --git a/src/bm.h b/src/bm.h
index 91b59f1..b4eae3b 100644
--- a/src/bm.h
+++ b/src/bm.h
@@ -197,11 +197,11 @@ void bm_push_native(Bm *bm, Bm_Native native);
 void bm_dump_stack(FILE *stream, const Bm *bm);
 void bm_load_program_from_file(Bm *bm, const char *file_path);

-#define BM_FILE_MAGIC 0x6D62
-#define BM_FILE_VERSION 5
+#define BM_FILE_MAGIC 0xa4016d62
+#define BM_FILE_VERSION 6

 PACK(struct Bm_File_Meta {
-    uint16_t magic;
+    uint32_t magic;
     uint16_t version;
     uint64_t program_size;
     uint64_t entry;
```

**Comment by catull** [comment]
If you read the resulting .bm file into an hex editor, with your suggestion @aodhneine, you can squint a naught, it reads

"bm" 1 $ - so we have a 1 dollar BM.

I am okay with this change.
