### ISSUE TITLE
SDL examples has a visual bug on Windows

### ISSUE THREAD

**Issue by rexim** [tsoding/bm#302]
![unknown](https://user-images.githubusercontent.com/165283/113879705-fd1ff600-97e4-11eb-9d4d-c81c6ea84ec4.png)

Discovered by @Ciremun

**Comment by kolumb** [comment]
I looked into bytes in `assets/tsodinW.raw` and found that there's `1a` sequence that makes file stop from further loading. When I replaced all instances of this bytes with anything else - it loads full image.
<details>

<summary> Examples </summary>

![123](https://user-images.githubusercontent.com/4366033/115241450-7f83b080-a129-11eb-99bf-15e6fe93f05f.jpg)

</details>

**Comment by Ciremun** [comment]
as @kolumb suggested, replacing all `1A`s with `00` in a hex editor helped! uwu~

<details>
<summary>image</summary>
<p><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/38132413/115243592-c5da0f00-a12b-11eb-8d17-1538934a471d.png"><img src="https://user-images.githubusercontent.com/38132413/115243592-c5da0f00-a12b-11eb-8d17-1538934a471d.png" alt="image" style="max-width:100%;"></a></p>
</details>

**Comment by kolumb** [comment]
I was reading about `fread` in [MSVC docs](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/fread?view=msvc-160#remarks) and found something in Remarks section. There's some replacement of end lines is happening if file is opened in text mode.
And it might be the case, because when I changed it to binary - original image file loaded completely:
<details>

<summary>git diff</summary>

```diff
@@ -116,7 +116,7 @@ int arena_slurp_file(Arena *arena, String_View file_path, String_View *content)
 {
     const char *file_path_cstr = arena_sv_to_cstr(arena, file_path);

-    FILE *f = fopen(file_path_cstr, "r");
+    FILE *f = fopen(file_path_cstr, "rb");
     if (f == NULL) {
         return -1;
     }
```

</details>

But tests are breaking then, they expect new line, or different kind of new line, not sure:
<details>

<summary>tests output example</summary>

```
. . .
[INFO] CMD: build\toolchain\bmr -p build\test\cases\read-write.bm -eo test\outputs\read-write.expected.out
test\outputs\read-write.expected.out:1: ERROR: Expected output differs from the actual one.
`   Expected line: `4294967295
    Actual   line: `4294967295`
[INFO] CMD: build\toolchain\bmr -p build\test\cases\rot13.bm -eo test\outputs\rot13.expected.out
test\outputs\rot13.expected.out:1: ERROR: Expected output differs from the actual one.
`   Expected line: `Hello, world! From ROT13.
    Actual   line: `Hello, world! From ROT13.`
```

</details>

**Comment by Ciremun** [comment]
pepega solution for tests
```diff
@@ -123,6 +123,12 @@ static void compare_outputs(const char *file_path, String_View expected, String_
         String_View expected_line = sv_chop_by_delim(&expected, '\n');
         String_View actual_line = sv_chop_by_delim(&actual, '\n');

+        if (*(expected_line.data + expected_line.count - 1) == '\r')
+        {
+            memset((char*)expected_line.data + expected_line.count - 1, 0, 1);
+            expected_line.count--;
+        }
+
         if (!sv_eq(expected_line, actual_line)) {
             fprintf(stderr, "%s:%zu: ERROR: Expected output differs from the actual one.\n",        
                     file_path, line_number);
```
