### ISSUE TITLE
Magic marker "BM" is already taken

### ISSUE THREAD

**Issue by catull** [tsoding/bm#70]
In trying to encode the `magic(5)` definitions for the `file(1)` utility, I discovered that the magic marker 'BM' is already used here [PC Bitmap](https://github.com/file/file/blob/master/magic/Magdir/images#L676).
It is documented [Bitmap file header](https://en.wikipedia.org/wiki/BMP_file_format#Bitmap_file_header).

Perhaps the Birtual Machine magic marker could be redefined as `БМ` or as 'bm'.

**Comment by rexim** [comment]
@catull interesting! Thanks for letting me know!

**Comment by catull** [comment]
Opened a feature request with maintainer of `file(1)` tool [issue 226](https://bugs.astron.com/view.php?id=226).

**Comment by catull** [comment]
It would display this on the BM image files:

```console
123f.bm:   Birtual Machine, version 1, program size 7, memory size 0, memory capacity 0
123i.bm:   Birtual Machine, version 1, program size 7, memory size 0, memory capacity 0
alloc.bm:  Birtual Machine, version 1, program size 7, memory size 0, memory capacity 0
bits.bm:   Birtual Machine, version 1, program size 14, memory size 0, memory capacity 0
e.bm:      Birtual Machine, version 1, program size 25, memory size 0, memory capacity 0
fib.bm:    Birtual Machine, version 1, program size 18, memory size 0, memory capacity 0
gray.bm:   Birtual Machine, version 1, program size 16, memory size 0, memory capacity 0
halt.bm:   Birtual Machine, version 260, program size 1, memory size 123456789, memory capacity 123456789
hello.bm:  Birtual Machine, version 1, program size 9, memory size 12, memory capacity 12
lerp.bm:   Birtual Machine, version 1, program size 35, memory size 0, memory capacity 0
memory.bm: Birtual Machine, version 1, program size 15, memory size 0, memory capacity 0
pi.bm:     Birtual Machine, version 1, program size 27, memory size 0, memory capacity 0
```

The `halt.bm` example above is a hacked one, where I manipulated the version and memory numbers in the code.

This allowed to verify larger numbers are saved and displayed correctly.
