### ISSUE TITLE
`b 0` in bdb results in "ERR : Cannot parse address or labels"

### ISSUE THREAD

**Issue by rexim** [tsoding/bm#87]
introduced in #76

**Comment by herrhotzenplotz** [comment]
This issue is closely linked to #86 .

The issue is that the `in` string in `bdb_parse_label_or_addr` contains a newline character. When we switch to parsing with `String_View`s as suggested in #86, we would naturally trim the input before doing anything else and eliminate this issue.

**Comment by rexim** [comment]
Resolved by #106
